version: "3"

services:

  oauth-simple-demo:
    image: node:10
    container_name: oauth-simple-demo
    volumes:
      - .:/opt/worbli/oauth/simple-demo
      - ../passport-worbli:/opt/worbli/oauth/passport-worbli
    ports:
      - '3030:3030'
    environment:
      PORT: 3030
      version: "3"
      NODE_ENV: development
    command:
    working_dir: /opt/worbli/oauth/simple-demo
    command: bash -c "npm i && npm start"

  oauth-server:
    image: node:10
    container_name: oauth-server
    volumes:
      - ../oauthFrontEndDesign:/opt/worbli/oauth/frontend
      - ../oauthBackEnd:/opt/worbli/oauth/backend
    links:
      - oauth-simple-demo
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: production
    working_dir: /opt/worbli/oauth/backend
    command:
      bash -c "npm i && npm i --prefix \"../frontend\" && npm run build --prefix \"../frontend\" && npm start"
      # bash -c "npm i && npm start"
